In [1]:
from tensorflow.keras.preprocessing.text import one_hot

In [2]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
type(sent)

list

In [4]:
## Define the vocabulary size
voc_size=10000

In [10]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [9]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[5325, 4430, 1142, 4296],
 [5325, 4430, 1142, 6574],
 [5325, 8633, 1142, 391],
 [4315, 2400, 8693, 576, 9780],
 [4315, 2400, 8693, 576, 2612],
 [5198, 5325, 5472, 1142, 4995],
 [3132, 3625, 4929, 576]]

In [11]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [12]:
import numpy as np

In [13]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 5325 4430 1142 4296]
 [   0    0    0    0 5325 4430 1142 6574]
 [   0    0    0    0 5325 8633 1142  391]
 [   0    0    0 4315 2400 8693  576 9780]
 [   0    0    0 4315 2400 8693  576 2612]
 [   0    0    0 5198 5325 5472 1142 4995]
 [   0    0    0    0 3132 3625 4929  576]]


In [14]:
## feature representation
dim=10

In [15]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [16]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [17]:
model.predict(embedded_docs)

1/1 [==============================] - 1s 1s/step


array([[[-2.18423735e-02,  4.68504168e-02,  4.34007160e-02,
          4.81207296e-03,  3.90503295e-02,  3.09800617e-02,
          2.20820419e-02, -4.78118658e-03,  4.64544445e-03,
          3.03970687e-02],
        [-2.18423735e-02,  4.68504168e-02,  4.34007160e-02,
          4.81207296e-03,  3.90503295e-02,  3.09800617e-02,
          2.20820419e-02, -4.78118658e-03,  4.64544445e-03,
          3.03970687e-02],
        [-2.18423735e-02,  4.68504168e-02,  4.34007160e-02,
          4.81207296e-03,  3.90503295e-02,  3.09800617e-02,
          2.20820419e-02, -4.78118658e-03,  4.64544445e-03,
          3.03970687e-02],
        [-2.18423735e-02,  4.68504168e-02,  4.34007160e-02,
          4.81207296e-03,  3.90503295e-02,  3.09800617e-02,
          2.20820419e-02, -4.78118658e-03,  4.64544445e-03,
          3.03970687e-02],
        [-4.36813124e-02,  1.55383386e-02, -4.04667631e-02,
         -3.22135575e-02, -4.26258221e-02, -4.67309356e-02,
         -5.54649904e-03,  4.71851118e-02,  5.908466

In [18]:
embedded_docs[0]

array([   0,    0,    0,    0, 5325, 4430, 1142, 4296])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 41ms/step


array([[-0.02184237,  0.04685042,  0.04340072,  0.00481207,  0.03905033,
         0.03098006,  0.02208204, -0.00478119,  0.00464544,  0.03039707],
       [-0.02184237,  0.04685042,  0.04340072,  0.00481207,  0.03905033,
         0.03098006,  0.02208204, -0.00478119,  0.00464544,  0.03039707],
       [-0.02184237,  0.04685042,  0.04340072,  0.00481207,  0.03905033,
         0.03098006,  0.02208204, -0.00478119,  0.00464544,  0.03039707],
       [-0.02184237,  0.04685042,  0.04340072,  0.00481207,  0.03905033,
         0.03098006,  0.02208204, -0.00478119,  0.00464544,  0.03039707],
       [-0.04368131,  0.01553834, -0.04046676, -0.03221356, -0.04262582,
        -0.04673094, -0.0055465 ,  0.04718511,  0.00590847, -0.04654534],
       [ 0.04518553, -0.02881771, -0.01137525,  0.01685121,  0.01268527,
        -0.02006449, -0.00885905, -0.0032495 ,  0.0415128 ,  0.01266165],
       [ 0.011316  , -0.01798016,  0.02285245,  0.04692948, -0.01576475,
        -0.04156988, -0.04485017,  0.01640649